import React from 'react'
import { Heart, ShieldCheck, HelpCircle, FileWarning } from 'lucide-react'
import Card from '../components/Card'

function About() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 py-4 sm:py-6 animate-fade-in text-[var(--text-color)]">
      {/* Page Title */}
      <div className="text-center max-w-2xl mx-auto space-y-2">
        <div className="inline-flex items-center justify-center bg-blue-50 dark:bg-slate-800 text-blue-600 dark:text-health-primary p-2 rounded-full mb-2">
          <Heart className="h-6 w-6" />
        </div>
        <h2 className="text-2xl sm:text-3xl font-extrabold text-[var(--text-color)]">
          Our HealthAI Philosophy
        </h2>
        <p className="text-xs sm:text-sm text-[var(--text-muted)] font-medium leading-relaxed">
          Discover why we built this awareness assistant, how our models process risks, and our strict commitment to proactive wellness education.
        </p>
      </div>

      {/* Strict Legal Disclaimer Callout */}
      <div className="bg-red-50/80 dark:bg-red-950/15 border-2 border-red-200 dark:border-red-900/40 p-6 rounded-2xl shadow-sm flex items-start gap-4">
        <div className="bg-red-100 dark:bg-red-900/40 p-3 rounded-2xl text-red-600 dark:text-red-400">
          <FileWarning className="h-6 w-6" />
        </div>
        <div className="space-y-2">
          <h3 className="font-extrabold text-red-700 dark:text-red-400 text-sm sm:text-base uppercase tracking-wider">
            ⚠️ IMPORTANT DISCLAIMER
          </h3>
          <p className="text-xs sm:text-sm text-red-650 dark:text-red-300/85 font-bold leading-relaxed">
            This system is not a medical diagnostic tool. It provides health risk awareness using AI models trained on medical datasets. Always consult a doctor for medical decisions.
          </p>
          <p className="text-xs sm:text-sm text-red-650 dark:text-red-300/80 font-medium leading-relaxed mt-2">
            All calculations generated by this platform are statistical risk awareness estimations designed strictly for educational reference and baseline trend tracking.
          </p>
        </div>
      </div>

      {/* Core Values grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="p-6 space-y-3">
          <div className="bg-blue-50 dark:bg-blue-950/20 p-2.5 rounded-xl text-blue-500 w-fit">
            <ShieldCheck className="h-5 w-5" />
          </div>
          <h4 className="font-extrabold text-sm sm:text-base text-[var(--text-color)]">
            Empathetic AI Explanations
          </h4>
          <p className="text-xs sm:text-sm text-[var(--text-muted)] leading-relaxed font-medium">
            We prioritize Explainable AI methodologies to ensure users understand exactly what baseline parameters contribute to their risk score. We strictly advocate transparency and layman terms.
          </p>
        </Card>

        <Card className="p-6 space-y-3">
          <div className="bg-emerald-50 dark:bg-emerald-950/20 p-2.5 rounded-xl text-emerald-500 w-fit">
            <HelpCircle className="h-5 w-5" />
          </div>
          <h4 className="font-extrabold text-sm sm:text-base text-[var(--text-color)]">
            Jargon-Free Accessibility
          </h4>
          <p className="text-xs sm:text-sm text-[var(--text-muted)] leading-relaxed font-medium">
            By translating confusing chemical panel names, clinical indicators, and enzymatic markers into clear, conversational layman's terms, we empower everyday individuals to understand their health trends easily.
          </p>
        </Card>
      </div>

      {/* Help block */}
      <Card className="p-6 text-center space-y-3">
        <h4 className="font-extrabold text-sm sm:text-base text-[var(--text-color)]">
          Do you suspect any active clinical warning signs?
        </h4>
        <p className="text-xs text-[var(--text-muted)] max-w-lg mx-auto font-medium">
          If you or your loved ones are experiencing acute symptoms (e.g. chest pain, sudden numbness, high fever, or breathing difficulty), contact your local hospital emergency clinic or medical dispatch services immediately.
        </p>
      </Card>
    </div>
  )
}

export default About
