import React from 'react'
import { Heart, ShieldCheck, HelpCircle, FileWarning } from 'lucide-react'
import Card from '../components/Card'

function About() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 py-4 sm:py-6 animate-fade-in">
      {/* Page Title */}
      <div className="text-center max-w-2xl mx-auto space-y-2">
        <div className="inline-flex items-center justify-center bg-blue-50 dark:bg-slate-800 text-blue-600 dark:text-health-primary p-2 rounded-full mb-2">
          <Heart className="h-6 w-6" />
        </div>
        <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white">
          Our HealthAI Philosophy
        </h2>
        <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 font-medium leading-relaxed">
          Discover why we built this awareness assistant, how our models process risks, and our strict commitment to clinical ethics.
        </p>
      </div>

      {/* Strict Legal Disclaimer Callout */}
      <div className="bg-red-50/80 dark:bg-red-950/15 border-2 border-red-200 dark:border-red-900/40 p-6 rounded-2xl shadow-sm flex items-start gap-4">
        <div className="bg-red-100 dark:bg-red-900/40 p-3 rounded-2xl text-red-600 dark:text-red-400">
          <FileWarning className="h-6 w-6" />
        </div>
        <div className="space-y-2">
          <h3 className="font-extrabold text-red-700 dark:text-red-400 text-sm sm:text-base uppercase tracking-wider">
            ⚠️ MANDATORY CLINICAL DISCLAIMER
          </h3>
          <p className="text-xs sm:text-sm text-red-650 dark:text-red-300/80 font-medium leading-relaxed">
            HealthAI is **NOT** a medical diagnostic tool. All risk scores, classifications, and explanations generated by this platform are simulated statistical estimations designed strictly for **educational awareness** and patient proactive baseline monitoring. 
          </p>
          <p className="text-xs sm:text-sm text-red-650 dark:text-red-300/80 font-bold leading-relaxed mt-2">
            Always consult a licensed physician or healthcare professional for official diagnosis, clinical treatment plans, or changes to medication regimens. Never self-diagnose or ignore professional care based on automated analytics.
          </p>
        </div>
      </div>

      {/* Core Values grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="p-6 space-y-3">
          <div className="bg-blue-50 dark:bg-blue-950/20 p-2.5 rounded-xl text-blue-500 w-fit">
            <ShieldCheck className="h-5 w-5" />
          </div>
          <h4 className="font-extrabold text-sm sm:text-base text-slate-800 dark:text-white">
            Ethical Machine Learning
          </h4>
          <p className="text-xs sm:text-sm text-slate-450 dark:text-slate-450 leading-relaxed font-medium">
            We prioritize Explainable AI methodologies (like SHAP attributions) to ensure users understand exactly what baseline parameters contribute to their risk score. We strictly advocate transparency.
          </p>
        </Card>

        <Card className="p-6 space-y-3">
          <div className="bg-emerald-50 dark:bg-emerald-950/20 p-2.5 rounded-xl text-emerald-500 w-fit">
            <HelpCircle className="h-5 w-5" />
          </div>
          <h4 className="font-extrabold text-sm sm:text-base text-slate-800 dark:text-white">
            Accessibility Mapped
          </h4>
          <p className="text-xs sm:text-sm text-slate-450 dark:text-slate-450 leading-relaxed font-medium">
            By translating confusing abbreviations, chemical panel names, and enzymatic markers into clear, conversational layman's terms, we empower everyday individuals to take charge of their health variables.
          </p>
        </Card>
      </div>

      {/* Help block */}
      <Card className="p-6 text-center space-y-3">
        <h4 className="font-extrabold text-sm sm:text-base text-slate-850 dark:text-white">
          Do you suspect any active clinical warning signs?
        </h4>
        <p className="text-xs text-slate-500 dark:text-slate-400 max-w-lg mx-auto font-medium">
          If you or your loved ones are experiencing acute symptoms (e.g. chest pain, leg swelling, sudden numbness, high fever), do not hesitate. Contact your local hospital emergency clinic or medical dispatch services immediately.
        </p>
      </Card>
    </div>
  )
}

export default About
