import React, { useState } from 'react'
import { Activity, ShieldCheck, Heart, Brain, FileText, TrendingUp, HelpCircle, ChevronDown, ChevronUp } from 'lucide-react'
import Card from '../components/Card'

function Home({ setPage }) {
  // Core features card list
  const features = [
    {
      icon: Activity,
      title: "Multi-Disease Prediction System",
      desc: "Instant risk estimation across 5 chronic health categories using a single unified dashboard.",
      color: "text-blue-500 bg-blue-500/10 border-blue-500/20"
    },
    {
      icon: ShieldCheck,
      title: "Simple Health Analysis",
      desc: "Layman-friendly scanning that takes your basic habits and indicators to compute clear safety metrics.",
      color: "text-emerald-500 bg-emerald-500/10 border-emerald-500/20"
    },
    {
      icon: TrendingUp,
      title: "Risk History Tracking",
      desc: "Record previous wellness predictions during your session and trace your improvement trends.",
      color: "text-purple-500 bg-purple-500/10 border-purple-500/20"
    },
    {
      icon: FileText,
      title: "Download Report (PDF Mock)",
      desc: "Compile your calculated risk scores and customized daily tips into a printable wellness summary.",
      color: "text-amber-500 bg-amber-500/10 border-amber-500/20"
    },
    {
      icon: Brain,
      title: "AI-Based Explanation System",
      desc: "Our interactive assistant answers 'Why this risk score?' using friendly everyday words.",
      color: "text-rose-500 bg-rose-500/10 border-rose-500/20"
    }
  ]

  // Frequently Asked Questions database
  const faqs = [
    {
      q: "Is HealthAI a replacement for a medical diagnosis?",
      a: "No, absolutely not. HealthAI is an educational wellness assistant designed to estimate potential risks and raise general health awareness. All outputs are statistical risk estimations and should never replace physical consultations, clinical diagnostic testing, or medication plans generated by your doctor."
    },
    {
      q: "How does the AI assistant estimate my health risk?",
      a: "The assistant matches your entered baseline metrics (e.g. age, blood pressure, sugar ranges) against verified medical research patterns. By analyzing correlations, it calculates a risk percentage pointing to how closely your metrics align with typical healthy vs high-risk groups."
    },
    {
      q: "Is my personal information uploaded to the cloud or saved?",
      a: "No, never. We value your privacy. All risk calculations and attributions happen locally within your active browser sandbox. We do not collect, store, or transmit your names, ages, or laboratory scores to any remote servers. Your information is 100% safe and private to you."
    },
    {
      q: "What should I do if my calculated risk level is Medium or High?",
      a: "First, stay calm. A high risk score does not mean you have a disease—it simply indicates that your metrics are outside standard healthy zones. We highly recommend scheduling a routine wellness screening with your primary healthcare provider to verify your scores and get professional guidance."
    }
  ]

  // Accordion state
  const [openFaq, setOpenFaq] = useState(null)

  const toggleFaq = (idx) => {
    if (openFaq === idx) {
      setOpenFaq(null)
    } else {
      setOpenFaq(idx)
    }
  }

  return (
    <div className="space-y-16 py-4 sm:py-6">
      {/* 1. Hero Section */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-center">
        {/* Left Side: Copywriting */}
        <div className="lg:col-span-7 space-y-6 text-center lg:text-left">
          <div className="inline-flex items-center gap-2 bg-blue-600/10 text-blue-600 dark:text-blue-400 px-3 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider select-none shadow-xxs">
            <Activity className="h-4 w-4 animate-pulse" />
            <span>AI Health Risk assistant</span>
          </div>

          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black leading-tight text-[var(--text-color)]">
            Understand Your <br />
            <span className="bg-gradient-to-r from-blue-600 to-emerald-500 bg-clip-text text-transparent">
              Health Risks Simply
            </span>
          </h1>

          <p className="text-base sm:text-lg lg:text-xl text-[var(--text-muted)] font-medium leading-relaxed max-w-xl mx-auto lg:mx-0">
            A friendly health awareness assistant that translates complex medical indicators into simple, easy-to-understand human language.
          </p>

          <div className="pt-2">
            <button
              onClick={() => setPage('predict')}
              className="px-8 py-4 bg-gradient-to-r from-blue-600 to-emerald-500 hover:from-blue-700 hover:to-emerald-600 text-white font-extrabold text-base rounded-2xl shadow-lg shadow-blue-500/15 hover:shadow-blue-500/35 hover:-translate-y-0.5 active:translate-y-0 active:scale-98 transition-all duration-200 cursor-pointer"
            >
              Check Your Health Risk
            </button>
          </div>
        </div>

        {/* Right Side: Reassuring Abstract Vector Graphic */}
        <div className="lg:col-span-5 flex justify-center">
          <div className="relative w-full max-w-[320px] aspect-square rounded-3xl bg-gradient-to-tr from-blue-500/10 to-emerald-500/10 flex items-center justify-center p-8 border border-[var(--card-border)] shadow-xs">
            <div className="absolute inset-0 bg-radial-gradient from-blue-400/20 to-transparent blur-2xl"></div>
            
            <svg viewBox="0 0 200 200" className="w-full h-full text-blue-600 dark:text-blue-400">
              <defs>
                <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="100%">
                  <stop offset="0%" stopColor="#2563EB" />
                  <stop offset="100%" stopColor="#10B981" />
                </linearGradient>
              </defs>
              <circle cx="100" cy="100" r="85" fill="none" stroke="url(#gradient)" strokeWidth="1.5" strokeDasharray="5 5" className="opacity-40 animate-spin" style={{ animationDuration: '40s' }} />
              <circle cx="100" cy="100" r="60" fill="none" stroke="currentColor" strokeWidth="0.5" className="opacity-20" />
              <path d="M 35 100 L 70 100 L 80 80 L 90 130 L 105 50 L 115 110 L 125 90 L 135 100 L 165 100" fill="none" stroke="url(#gradient)" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" className="pulse-glow" />
              <circle cx="105" cy="50" r="4.5" fill="#10B981" />
              <circle cx="90" cy="130" r="4.5" fill="#2563EB" />
            </svg>
          </div>
        </div>
      </div>

      {/* 2. Features Showcase Section */}
      <div className="space-y-8">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold text-[var(--text-color)]">
            Designed for Health Awareness
          </h2>
          <p className="text-xs sm:text-sm text-[var(--text-muted)] font-medium">
            Discover the wellness support features integrated within this friendly risk checker.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-6">
          {features.map((f, idx) => {
            const Icon = f.icon
            return (
              <Card key={idx} className="flex flex-col items-center text-center p-6 space-y-4 hover:border-blue-500/25">
                <div className={`p-3 rounded-2xl border ${f.color} shadow-sm`}>
                  <Icon className="h-6 w-6" />
                </div>
                <h3 className="font-extrabold text-sm sm:text-base text-[var(--text-color)]">
                  {f.title}
                </h3>
                <p className="text-xs text-[var(--text-muted)] leading-relaxed font-medium">
                  {f.desc}
                </p>
              </Card>
            )
          })}
        </div>
      </div>

      {/* 3. Deep Scrollable Frequently Asked Questions (FAQ) Section */}
      <div className="space-y-8 border-t border-[var(--card-border)] pt-12">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <div className="inline-flex items-center justify-center bg-emerald-500/10 text-emerald-500 p-2 rounded-full mb-1">
            <HelpCircle className="h-6 w-6" />
          </div>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-[var(--text-color)]">
            Frequently Asked Questions
          </h2>
          <p className="text-xs sm:text-sm text-[var(--text-muted)] font-medium">
            Learn more about our health estimations, data privacy standards, and clinical guidelines.
          </p>
        </div>

        <div className="max-w-3xl mx-auto space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openFaq === idx
            return (
              <div 
                key={idx} 
                className="bg-[var(--card-bg)] border border-[var(--card-border)] rounded-2xl overflow-hidden transition-all duration-300 shadow-sm"
              >
                {/* Header Question */}
                <button
                  onClick={() => toggleFaq(idx)}
                  className="w-full flex justify-between items-center p-5 text-left font-bold text-sm sm:text-base text-[var(--text-color)] hover:bg-slate-100/30 dark:hover:bg-slate-800/20 transition-colors duration-200 cursor-pointer"
                >
                  <span>{faq.q}</span>
                  {isOpen ? (
                    <ChevronUp className="h-5 w-5 text-blue-500" />
                  ) : (
                    <ChevronDown className="h-5 w-5 text-[var(--text-muted)]" />
                  )}
                </button>

                {/* Answer drawer */}
                {isOpen && (
                  <div className="p-5 pt-0 border-t border-[var(--card-border)] bg-slate-50/50 dark:bg-slate-800/10 transition-all duration-200">
                    <p className="text-xs sm:text-sm text-[var(--text-muted)] font-medium leading-relaxed mt-4">
                      {faq.a}
                    </p>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}

export default Home
