[theme]
primaryColor = "#00f0ff"
backgroundColor = "#0a0b10"
secondaryBackgroundColor = "#121420"
textColor = "#f8f9fa"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
